### ISSUE TITLE
Check for a passphrase prompt

### ISSUE THREAD

**Issue by vernistage** [riboseinc/rspec-pgp_matchers#33]
https://github.com/riboseinc/rspec-pgp_matchers/blob/89a02228550fef73ea378b39827dd8fd84624d05/lib/rspec/pgp_matchers/gpg_runner.rb#L16

Is this method checking for a passphrase prompt? I'm trying to implement this gem, but it's failing to recognize a legitimate PGP message. I'm wondering if it's because my CLI is prompting me to enter a passphrase, and that doesn't match this checker.  Thanks for clarification.

![Screen Shot 2019-08-14 at 10 29 21 AM](https://user-images.githubusercontent.com/15304234/63034165-6881bb00-be7e-11e9-8e8e-5c736ef8c94e.png)

**Comment by ronaldtse** [comment]
@vernistage thanks for reporting this! @skalee could you help check this?

**Comment by skalee** [comment]
@vernistage Yes, this is because of decryption key is password-protected. As a general advice, I recommend not to use such keys in tests. It saves a lot of hassle.

I am thinking about some kind of support for that. I am against implementing it in gem's API (it would become very complicated when given message is encrypted for many recipients), however I have several other ideas already. Possible solutions include [presetting keys](https://wincent.com/wiki/Using_gpg-agent_on_OS_X), allow customization of GnuPG to be executed (which would effectively allow passing passwords via CLI arguments), or even implementing a custom pinentry.

BTW if you need an example how to create unprotected keys in batch, see `Rakefile`.

**Comment by skalee** [comment]
@vernistage See https://github.com/riboseinc/rspec-pgp_matchers/blob/master/PROTECTED_KEYS.adoc.

**Comment by vernistage** [comment]
That makes total sense, and as far as I can see, you all are the only ones doing what you're doing. I don't think the gem is going to work for my specific requirements, but that's OK.

**Comment by skalee** [comment]
It is unlikely that this gem will be usable for anything but testing anytime soon. This is because it relies on parsing human-readable output from GnuPG, which is subject to changes and error-prone in general. There is the issue #16 all about migrating to machine-readable GnuPG output format, however this is going to be difficult and not going to be done soon. Main obstacles are that the machine-readable output is missing some information which has to be extracted in some other way, and that the format is poorly documented.
